### ISSUE TITLE
Add options for saving, closing or keeping taggs

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#12]
Entries Edit entry  

there is two buttons on the bottom right. I suggest to add a third one. We would have "save and close" (and go back to the entries main frame, as it is now), a button "Save and keep" (entry is saved but the excerpt and the options previously selected stays in the view. THi sis quite useful when you need to just change one option or on location or one sectror and a severity level) and a button "save and add another" where the list of options previously selectd and the excerpt windows are cleared and we can add a new exceprt from the same lead.

**Comment by oiime** [comment]
can you list all the fields that should be forwarded to the next entry?

**Comment by patricechataigner** [comment]
All the fields that are above the map, including the location on the map (Point, area or polygon) should be saved and tranferred into the next entry. starting at "Sector", the field should be reset

**Comment by oiime** [comment]
k
