### ISSUE TITLE
URGENT: New Domain Issue

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#18]
I ran into 2 problems when creating a new domain:
- I've created a new Domain (Europe RefugeeMigrant Crisis), but it doesn't appear under 'select Domain'
- When creating a domain, I’m not able to add Serbia and Montenegro (seems to be a bug specifically for that tag)

Thanks!

**Comment by oiime** [comment]
- You need to do a full refresh to see a domain you just added (ctrl+shift+r) 
- Yeah, the countries list was out of date (pre 2006 I assume), refresh and it should be fine now

**Comment by LeonieTax** [comment]
Great, thanks for your quick response!
