### ISSUE TITLE
Lead: Unexpected error

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#19]
![error screenshot](https://cloud.githubusercontent.com/assets/9335284/11614102/1458f1ae-9c38-11e5-8fb8-82569bff1abc.png)

Unexpected error occurs when trying to upload a new lead.

**Comment by LeonieTax** [comment]
Update: This happens when trying to add a 2nd lead (so after using 'save and add another' instead of just 'save')

**Comment by oiime** [comment]
fixed, refresh
