### ISSUE TITLE
Export button difficult to select/hover

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#2]
General Export  

The export button are difficult to select when you hover. not sure why. Important for us to have a denormlaized export function, same format as the one used for the HIRA.

**Comment by oiime** [comment]
not noticing that, can you give me the exact browser version (try to clear cache on the site maybe)

also uploaded a denormalize version (do a full refresh), the csv format is still lacking as i'm waiting for a more concrete format. can open that in a different ticket.

**Comment by patricechataigner** [comment]
UInder firefox i have difficulties selecting, but not under chrome... we will recommend using chrome for this, no problem.

**Comment by patricechataigner** [comment]
Working perfect now on firefox.. topic closed
