### ISSUE TITLE
Entry: Country

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#21]
Some information snippets refer to a country that's not on the list or concerns a region. Is it possible to add 'other' and 'regional' as options? Thanks!

**Comment by oiime** [comment]
I'm not sure I understand what you mean

**Comment by LeonieTax** [comment]
Create entry - Country - Select affected country

The list of affected countries is limited to the countries assigned to the domain. However, relevant information can cover other countries or sets of countries. Does that make sense?

**Comment by oiime** [comment]
I guess in this case those countries should be added to the domain. the list of countries in the domain are countries that are relevant for data entry, not necessarily those affected.

**Comment by LeonieTax** [comment]
And what if the information concerns a whole region (e.g. X people have entered Europe in 2015)

**Comment by oiime** [comment]
Currently country is mandatory, Can maybe have "No Specific Country" as an option in the pulldown. Regions are an issue as that might have statistical implications afterwards (to which country to attribute an entry)

**Comment by LeonieTax** [comment]
Ok - you can change into 'multiple-countries'. Or can I do this myself?

**Comment by oiime** [comment]
You should now have an "No Country" option at the end of the pulldown within the entry edit, refresh.

**Comment by LeonieTax** [comment]
Sorry to be picky on this, but 'no country' will just be confusing. Either 'other' or 'multiple countries'. Thanks a lot!

**Comment by oiime** [comment]
Would be updated on the next upload, already closed the laptop.

**Comment by LeonieTax** [comment]
Sure, not urgent. Have a good evening!
