### ISSUE TITLE
Change tags for specific domain

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#22]
Hi! Can I change the tags for specific domain (in this case Europe RefugeeMigrant Crisis) without it affecting the tags for the other domains?

**Comment by oiime** [comment]
Should be part of a bigger ticket to customize domains, there is already a base for it but we need to think exactly what we want (eg: edit domain accessibility when editing the tags, allow different users to manage different domains etc)

**Comment by LeonieTax** [comment]
Hi! I'm not a 100% sure that I understand what you mean. Let me explain a bit better what I mean. For the domain 'Europe RefugeeMigrant Crisis' I want to significantly simplify the entry section. I for instance want to get rid of all the 'children' under sectors and only keep the 'parents'. However, for other crises this type of detail remains important so I do not want to delete tags for all domains. Does this make sense?

**Comment by oiime** [comment]
Yeah, that's what I mean. Just thinking about the best way to manage it as it can go in different directions (making sections not mandatory, adding some values, removing others etc)

**Comment by LeonieTax** [comment]
Ok, it would be great if we could fix this asap, as I can't really start using the platform without adapting it. Thanks for all your help on this!

**Comment by oiime** [comment]
That'll take a while, can't start without? wasn't a problem in any of the previous versions.

**Comment by LeonieTax** [comment]
What I mean is that we cant start entering data & training people on how to enter data if we're adapting fields for entry later. And I don't want to adapt the fields for entry if that affects all domains. If it is not possible to separate the different domains anytime soon, just let me know, than we'll work around it.

**Comment by oiime** [comment]
I think it's best to start with the existing tags, there are a lot of issues to consider before making different tags such as integration and having consistent values between domains for analysis. let's set some time to discuss this with patrice maybe and see what'll be the best way to go about it.

**Comment by patricechataigner** [comment]
instead of changing the list of taggs for each crisis, wich would actually create a lot of discrepancies when aggregating between countries or visualizing in the main map, i would suggest we have the possibility to hide some tags (to limit the number of response options) within some specific countries. Agree that the current list is not adapted to the migrant crisis, but we could solve this just by letting the admin chosing which response options can appear. Feasible?

**Comment by oiime** [comment]
I've added the option to exclude a specific tag class from a list of domains, accessible via the admin/tag_class

**Comment by LeonieTax** [comment]
Great, thanks. But instead of having this for the general tag (e.g. Underlying Factor), can we have it for the separate categories (e.g. Underlying Factor / Availability / Stock)? Thanks a lot!

**Comment by oiime** [comment]
Not sure I understand, what do you mean?

**Comment by LeonieTax** [comment]
Take for instance the tag 'sector' - I want to keep the possibility to tag a parent (WASH), but delete the child (WASH/ Sanitation) for a specific domain. Does that make sense?

**Comment by oiime** [comment]
That's the thing I wanted to avoid, it could have a lot of side effects. If it's crucial for this instance I can try to patch something up. if not, I think it'll be good to start without it.

**Comment by LeonieTax** [comment]
Ok, In my opinion the positive effects of having a light tagging system for some crises outweigh the negative effects on cross-country comparison, but let's not rush into it right now. The one thing I would love before launching the platform is to be able to assign leads to people (see other GitHub issue). Is that an option?
