### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#25]
Hi Itamar, User Andrej Verity (OCHA) cannot log to the system. When going to the user management window I can t delete either the user from the list so he can try to log again. Cheers!

**Comment by oiime** [comment]
I've removed the user manually, you can recreate it. You can't actually delete a user as they might be associated with leads/entries, We can add a ticket though to reset a user password (send email to reset it)

**Comment by LeonieTax** [comment]
Hi Itamar - I'm having the same problem with new team members, they cannot sign up & I cannot delete them. How to fix this?

**Comment by oiime** [comment]
#31
