### ISSUE TITLE
Leads: Confidentiality

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#28]
Hi! We often receive information that is sensitive and should not be shared widely. Therefore, we assign levels of confidentiality to the information received which influences how we can use and source the information in our reports. 

Could you add an extra category 'confidentiality level' under 'Entry Leads' (after Description), with the following 4 levels:
1. Unprotected
2. Protected
3. Restricted
4. Confidential

One there is agreement on how we make the SIDR accessible to the public, we need to discuss what to do with information sources level 2,3 & 4.

Thank you!

**Comment by oiime** [comment]
You mean as a Lead property or as an Entry property?

**Comment by oiime** [comment]
done

**Comment by LeonieTax** [comment]
Thank you!
