### ISSUE TITLE
URGENT: Extra tags entries

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#29]
HI!

I just discussed with Patrice and we'll need an extra tag with 2 parents added to the entry section:

Tag: Crisis Drivers

Parent: Political developments 

Children:

EU level
National level
Other (as appropriate for the specific emergency)

Parent: Conflict developments 

Children:

Change in area of control
Offense
Security incident
Peace agreement/Truce
Other (as appropriate for the specific emergency)

Would that work? Thanks!

**Comment by oiime** [comment]
I'm not sure I understand, you want to dynamically add tag types? I thought the current tag types list was permanent. This needs to be properly clarified.

**Comment by LeonieTax** [comment]
No, not dynamically add tag types. We 'forgot' one important category in the tag types list. The suggested category is a one that we do normally use within our tagging.

**Comment by oiime** [comment]
ok, added, edit the values in the admin section so it'll work (refresh afterwards)

**Comment by LeonieTax** [comment]
Hi, Sorry I might not have been completely clear: the main tag is 'Crisis Drivers'. The dropdown menu should give the parents (Political developments + children, Conflict developments + children). I can put this is in a spreadsheet if this is easier for you?

**Comment by oiime** [comment]
fixed, refresh

**Comment by LeonieTax** [comment]
Great - but there are no parents in the crisis driver category?

**Comment by oiime** [comment]
you create them yourself in the admin, once you add a tag you can use it as parent

**Comment by LeonieTax** [comment]
Ah, yes! Thanks!
