### ISSUE TITLE
URGENT: User management

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#31]
HI!

This is quite urgent: we want to start using the platform with our team but for some reason people cannot sign up. They are getting a message that they've already registered. I cannot delete them from the user list. Do you know how to fix this?

Thanks!

**Comment by oiime** [comment]
I have added an option to reset password, it has a link in the login page

**Comment by LeonieTax** [comment]
HI - thanks for your response. But that did not solve the issue. After people 'register a new membership' it says 'email already exists'. When trying to use that email and password nothing happens after pushing the 'sign in' button.

**Comment by oiime** [comment]
The email and password should work perfectly fine in signin, checked.

The problem was that people double-clicked on the register button, I have changed it to go to home after registration now.

**Comment by LeonieTax** [comment]
Ok, now it works. Thank you!
