### ISSUE TITLE
Entry Export to CSV

### ISSUE THREAD

**Issue by LeonieTax** [oiime/sidr#32]
Hola,

When exporting the list of entries to CSV only a part of the columns is exported. The following tags are missing:
- Geographic location
- Severity
- Reliability
- Timeline

**Comment by oiime** [comment]
k, updated. let's set some time afterwards to reopen the whole geographical thing because it'll be quite difficult to read the geojson coordinates in csv format.

**Comment by LeonieTax** [comment]
Hi! I discovered that the excerpt is also not available when exported to CSV. Thanks for adding!
