### ISSUE TITLE
Make field description non mandatory

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#6]
Leads   Create leads    

The field description is not necessary. at this stage we are uniquely loading documents, Name, source, URL, website (automatically extracted, that s great!), publication date and the ability to upload the document are sufficient

**Comment by oiime** [comment]
Remove the field completely or just make non-mandatory?

**Comment by patricechataigner** [comment]
Just make it non mandatory

**Comment by oiime** [comment]
It's only for manual lead (not a url or an attachment), meaning it'll only be used when you want to paste raw text

**Comment by patricechataigner** [comment]
OK got it! excellent. topic close
