### ISSUE TITLE
Possibility to do search or filtering by user

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#7]
Entries Main frame  

Is it possible to do a search by user (useful to see who is overestimating severity level for instance). It would be useful to do a search fro several "organization" together, or tags, or locations or severity level ( in fact, make them all multiple choice). finally, a button to clear all filters would be great.

**Comment by oiime** [comment]
Duplicate of #8

**Comment by patricechataigner** [comment]
You are right.. Issue is closed and transfered to #8
