### ISSUE TITLE
Change header "entry status" by "status"

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#9]
Entries Main frame  

The header "Entry status" should be changed in "Status" only

**Comment by oiime** [comment]
There are two statuses, the status of the entry as related to actions taken and the status as related to the data entry (active/inactive), need to decide how to treat them

**Comment by patricechataigner** [comment]
Please keep Status and replace "Entry status" by "Group status"

**Comment by patricechataigner** [comment]
Please keep "status" as it is and replace "Entry status" by "group status"

**Comment by oiime** [comment]
k
